json.id resource.id
json.name resource.name
json.order_no resource.order_no
json.crm_customer_id resource.crm_customer_id
json.customer_name resource.crm_customer&.name
json.contact_id resource.contact_id
json.crm_opportunity_id resource.crm_opportunity_id
json.owner_id resource.owner_id
json.owner_name resource.owner&.name
json.status resource.status
json.order_date resource.order_date
json.delivery_date resource.delivery_date
json.order_currency resource.order_currency
json.exchange_rate resource.exchange_rate
json.order_amount_micros resource.order_amount_micros
json.cost_amount_micros resource.cost_amount_micros
json.profit_amount_micros resource.profit_amount_micros
json.profit_rate resource.profit_rate
json.remark resource.remark
json.created_at resource.created_at
json.updated_at resource.updated_at
