json.id resource.id
json.name resource.name
json.sku resource.sku
json.category resource.category
json.product_line resource.product_line
json.specification resource.specification
json.unit resource.unit
json.cost_price_micros resource.cost_price_micros
json.sale_price_micros resource.sale_price_micros
json.pricing_currency resource.pricing_currency
json.is_active resource.is_active
json.remark resource.remark
json.updated_at resource.updated_at
