json.id resource.id
json.name resource.name
json.crm_customer_id resource.crm_customer_id
json.customer_name resource.crm_customer&.name
json.owner_id resource.owner_id
json.amount_micros resource.amount_micros
json.currency resource.currency
json.sales_stage resource.sales_stage
json.probability resource.probability
json.expected_close_date resource.expected_close_date
json.current_need resource.current_need
json.competitor resource.competitor
json.loss_reason resource.loss_reason
json.next_action resource.next_action
json.last_activity_at resource.last_activity_at
json.opportunity_remark resource.opportunity_remark
json.created_at resource.created_at
json.updated_at resource.updated_at
