json.id resource.id
json.name resource.name
json.quote_no resource.quote_no
json.crm_customer_id resource.crm_customer_id
json.customer_name resource.crm_customer&.name
json.contact_id resource.contact_id
json.crm_opportunity_id resource.crm_opportunity_id
json.owner_id resource.owner_id
json.quote_date resource.quote_date
json.valid_until resource.valid_until
json.status resource.status
json.quote_currency resource.quote_currency
json.exchange_rate resource.exchange_rate
json.subtotal_micros resource.subtotal_micros
json.discount_amount_micros resource.discount_amount_micros
json.shipping_fee_micros resource.shipping_fee_micros
json.tax_amount_micros resource.tax_amount_micros
json.total_amount_micros resource.total_amount_micros
json.line_items_count resource.line_items.size
json.remark resource.remark
json.updated_at resource.updated_at
