json.id resource.id
json.kind resource.kind
json.item_type resource.item_type
json.mes_material_id resource.mes_material_id
json.material_name resource.mes_material&.name
json.crm_product_id resource.crm_product_id
json.product_name resource.crm_product&.name
json.production_order_id resource.production_order_id
json.production_order_no resource.production_order&.order_no
json.production_order_owner_name resource.production_order&.owner&.name
json.inspected_qty resource.inspected_qty
json.passed_qty resource.passed_qty
json.failed_qty resource.failed_qty
json.result resource.result
json.defect_reason resource.defect_reason
json.need_rework resource.need_rework
json.inspector_id resource.inspector_id
json.inspector_name resource.inspector&.name
json.inspected_at resource.inspected_at
json.remark resource.remark
