json.id resource.id
json.production_order_id resource.production_order_id
json.production_order_no resource.production_order&.order_no
json.operation_name resource.operation_name
json.qty_completed resource.qty_completed
json.qty_returned resource.qty_returned
json.qty_scrap resource.qty_scrap
json.operator_id resource.operator_id
json.operator_name resource.operator&.name
json.recorded_at resource.recorded_at
json.remark resource.remark
json.created_at resource.created_at
