json.id resource.id
json.mes_material_id resource.mes_material_id
json.material_name resource.mes_material&.name
json.material_no resource.mes_material&.material_no
json.qty resource.qty
json.unit resource.unit
json.rate_micros resource.rate_micros
json.amount_micros resource.amount_micros
json.remark resource.remark
