json.id resource.id
json.mes_material_id resource.mes_material_id
json.material_no resource.material_no
json.material_name resource.material_name
json.category resource.category
json.specification resource.specification
json.qty resource.qty
json.unit resource.unit
json.remark resource.remark
