json.id resource.id
json.department_id resource.department_id
json.department_name resource.department&.name
json.department_leader_id resource.department&.leader_id
json.department_leader_name resource.department&.leader&.name
json.user_id resource.user_id
json.user_name resource.user.name
json.user_email resource.user.email
json.thumbnail resource.user.avatar_url
json.title resource.title
json.is_primary resource.is_primary
